module BillHicks
  class BrandConverter

    def self.convert(value)
      if brand = self.brands.detect {|brand| brand[:prefix] == value.split[0] }
        brand[:company].empty? ? value.split[0] : brand[:company]
      else
        value.split[0]
      end
    end

    def self.brands
      @@brands ||= [
        { prefix: "2A", company: "2A ARMAMENT" },
        { prefix: "AAE", company: "AA&E" },
        { prefix: "ADAMS", company: "ADAMS ARMS" },
        { prefix: "AAC", company: "ADVANCED ARMAMENT" },
        { prefix: "AT", company: "ADVANCED TECHNOLOGY, INC." },
        { prefix: "AMK", company: "TENDER CORPORATION-US" },
        { prefix: "AGU", company: "TEXAS ARMAMENT & TECHNOLOGY" },
        { prefix: "AS", company: "AIMSHOT" },
        { prefix: "AIM", company: "AIMTECH MOUNT SYSTEMS" },
        { prefix: "APF", company: "ALEX PRO FIREARMS LLC" },
        { prefix: "KIT", company: "ALEX PRO FIREARMS LLC" },
        { prefix: "ALLEN", company: "ALLEN COMPANY INC." },
        { prefix: "ATI", company: "AMERICAN TACTICAL IMPORTS" },
        { prefix: "AM", company: "ANDERSON MANUFACTURING" },
        { prefix: "ARMA", company: "ARMALITE INC." },
        { prefix: "APO", company: "ARROW PRECISION, LLC" },
        { prefix: "ARS", company: "ARSENAL, INC." },
        { prefix: "ATN", company: "ATN" },
        { prefix: "AO", company: "AUTO-ORDNANCE" },
        { prefix: "BAR", company: "BARNES BULLETS, INC." },
        { prefix: "BARN", company: "BARNETT CROSSBOWS" },
        { prefix: "BARR", company: "BARRETT FIREARMS MFG INC" },
        { prefix: "BARS", company: "BARSKA OPTICS" },
        { prefix: "BARSKA", company: "BARSKA OPTICS" },
        { prefix: "BOG", company: "BATTENFELD" },
        { prefix: "CW", company: "BATTENFELD" },
        { prefix: "FRANK", company: "BATTENFELD" },
        { prefix: "HOOY", company: "BATTENFELD" },
        { prefix: "LD", company: "BATTENFELD" },
        { prefix: "TIP", company: "BATTENFELD" },
        { prefix: "WH", company: "BATTENFELD" },
        { prefix: "BXB", company: "BEAR ARCHERY" },
        { prefix: "BER", company: "BERETTA USA" },
        { prefix: "BM", company: "BERRY'S MANUFACTURING" },
        { prefix: "BC", company: "BIRCHWOOD LABORATORIES, INC." },
        { prefix: "SL", company: "BIRCHWOOD LABORATORIES, INC." },
        { prefix: "BR", company: "BLACK RAIN ORDNANCE, INC." },
        { prefix: "BH", company: "BLACKHAWK" },
        { prefix: "KNOXX", company: "BLACKHAWK" },
        { prefix: "BB", company: "BLUE BOOK PUBLICATIONS" },
        { prefix: "BOB", company: "BOBERG ARMS CORPORATION" },
        { prefix: "BOND", company: "BOND ARMS, INC." },
        { prefix: "BRO", company: "BROWNING" },
        { prefix: "BSA", company: "BSA OPTICS" },
        { prefix: "BUCK", company: "BUCK KNIVES INC" },
        { prefix: "BD", company: "BULLDOG CASES" },
        { prefix: "BUR", company: "BURRIS COMPANY, INC" },
        { prefix: "BF", company: "BUSHMASTER" },
        { prefix: "BUS", company: "BUSHNELL INC." },
        { prefix: "MILLET", company: "BUSHNELL INC." },
        { prefix: "RUB", company: "BUSHNELL INC." },
        { prefix: "SIM", company: "BUSHNELL INC." },
        { prefix: "TAS", company: "BUSHNELL INC." },
        { prefix: "BS", company: "BUSHNELL INC." },
        { prefix: "BUT", company: "BUSHNELL INC." },
        { prefix: "GM", company: "BUSHNELL INC." },
        { prefix: "HOP", company: "BUSHNELL INC." },
        { prefix: "SP", company: "BUSHNELL INC." },
        { prefix: "UM", company: "BUSHNELL INC." },
        { prefix: "CPD", company: "C PRODUCTS DEFENSE, INC." },
        { prefix: "CAA", company: "ME TECHNOLOGY, INC." },
        { prefix: "C4F", company: "2517 INC" },
        { prefix: "CE", company: "EASTMAN OUTDOORS, INC." },
        { prefix: "CDLY", company: "KBI INC" },
        { prefix: "CARL", company: "CARLSON'S" },
        { prefix: "CP", company: "CENTER POINT" },
        { prefix: "CA", company: "CHARTER ARMS" },
        { prefix: "CF", company: "CHIAPPA FIREARMS USA, LTD." },
        { prefix: "CIM", company: "CIMARRON FIREARMS CO INC." },
        { prefix: "CFA", company: "CIVILIAN FORCE ARMS" },
        { prefix: "CMC", company: "CMC" },
        { prefix: "CMMG", company: "COMMERCIAL MARKETING LLC" },
        { prefix: "COBRA", company: "COBRA" },
        { prefix: "CLT", company: "COLT'S MANUFACTURING" },
        { prefix: "TALO CLT", company: "COLT'S MANUFACTURING" },
        { prefix: "CR", company: "BOLD IDEAS" },
        { prefix: "COR", company: "CORBON AMMO" },
        { prefix: "GLASER", company: "CORBON AMMO" },
        { prefix: "C15", company: "GOOD TIME OUTDOORS INC" },
        { prefix: "COV", company: "COVERT" },
        { prefix: "KSA", company: "KEYSTONE SPORTING ARMS, LLC" },
        { prefix: "CTC", company: "CRIMSON TRACE CORPORATION" },
        { prefix: "BEN", company: "CROSMAN CORPORATION" },
        { prefix: "CROS", company: "CROSMAN CORPORATION" },
        { prefix: "NT", company: "NON TYPICAL  (CUDDEBACK)" },
        { prefix: "BERG", company: "BPI OUTDOORS" },
        { prefix: "BGA", company: "BPI OUTDOORS" },
        { prefix: "CVA", company: "BPI OUTDOORS" },
        { prefix: "QUA", company: "BPI OUTDOORS" },
        { prefix: "CZ", company: "CZ-USA" },
        { prefix: "DAISY", company: "DAISY OUTDOOR PRODUCTS" },
        { prefix: "DDI", company: "DESTRUCTIVE DEVICES INDUSTRIES" },
        { prefix: "DAIR", company: "BP FIREARMS COMPANY, LLC" },
        { prefix: "DTI", company: "DEL-TON, INC." },
        { prefix: "DES", company: "DESANTIS HOLSTER & LEATHER" },
        { prefix: "DBF", company: "DIAMONDBACK FIREARM LLC" },
        { prefix: "TALO DBF", company: "DIAMONDBACK FIREARM LLC" },
        { prefix: "DH", company: "DIAMONDHEAD USA, INC." },
        { prefix: "DA", company: "DICKINSON, LLC" },
        { prefix: "BEAR", company: "DKG TRADING INC." },
        { prefix: "CENT", company: "DKG TRADING INC." },
        { prefix: "DKG", company: "DKG TRADING INC." },
        { prefix: "FM", company: "DKG TRADING INC." },
        { prefix: "NS", company: "DKG TRADING INC." },
        { prefix: "DAT", company: "DO-ALL OUTDOORS" },
        { prefix: "DOG", company: "DOGTRA COMPANY" },
        { prefix: "DSC", company: "DOUBLESTAR CORPORATION" },
        { prefix: "DTD", company: "DOUBLETAP DEFENSE LLC." },
        { prefix: "DPMS", company: "DPMS FIREARMS" },
        { prefix: "DRA", company: "DRAGO GEAR" },
        { prefix: "DSA", company: "DSA, INC." },
        { prefix: "DT", company: "DT SYSTEMS, INC." },
        { prefix: "EAA", company: "EAA, CORP" },
        { prefix: "EI", company: "EAGLE IMPORTS INC (BERSA)" },
        { prefix: "EOT", company: "L-3 COMMUNICATIONS-EO TECH" },
        { prefix: "ERGO", company: "FALCON INDUSTRIES INC" },
        { prefix: "EST", company: "FEDERAL AMMO" },
        { prefix: "FED", company: "FEDERAL AMMO" },
        { prefix: "IND", company: "FEDERAL AMMO" },
        { prefix: "FIO", company: "FIOCCHI OF AMERICA" },
        { prefix: "WILL", company: "WILLIAMS GUN SIGHT COMPANY" },
        { prefix: "FC", company: "FLIPPIN CRITTERS" },
        { prefix: "FLITZ", company: "FLITZ INTERNATIONAL LTD" },
        { prefix: "FMK", company: "FMK FIREARMS, INC." },
        { prefix: "FNH", company: "FN AMERICA, LLC" },
        { prefix: "FOBUS", company: "FIRST SAMCO/FOBUS HOLSTER" },
        { prefix: "FA", company: "FRANKLIN ARMORY" },
        { prefix: "G2R", company: "G2 RESEARCH, INC" },
        { prefix: "G96", company: "G96 PRODUCTS CO INC." },
        { prefix: "GAL", company: "GALCO GUNLEATHER" },
        { prefix: "GAMO", company: "GAMO OUTDOOR USA" },
        { prefix: "GATCO", company: "GATCO" },
        { prefix: "TIMB", company: "GATCO" },
        { prefix: "GEM", company: "GEM-TECH" },
        { prefix: "GERBER", company: "GERBER" },
        { prefix: "GMG", company: "GLOBAL MILITARY GEAR" },
        { prefix: "GLOCK", company: "GLOCK" },
        { prefix: "MISC", company: "GLOCK" },
        { prefix: "TALO GLOCK", company: "GLOCK" },
        { prefix: "GOAL", company: "GOAL ZERO, LLC" },
        { prefix: "GRAB", company: "GRABBER INC" },
        { prefix: "GRIF", company: "" },
        { prefix: "GT", company: "GROVTEC US, INC." },
        { prefix: "CYC", company: "GSM, LLC" },
        { prefix: "STC", company: "GSM, LLC" },
        { prefix: "WALK", company: "GSM, LLC" },
        { prefix: "WRC", company: "GSM, LLC" },
        { prefix: "GV", company: "GUNVAULT" },
        { prefix: "HK", company: "HECKLER & KOCH, INC." },
        { prefix: "NEF", company: "H & R 1871" },
        { prefix: "HAR", company: "HARRIS BIPODS" },
        { prefix: "HWK", company: "HAWKE SPORT OPTICS" },
        { prefix: "HC", company: "HC MAGS, LLC" },
        { prefix: "HD", company: "HEIZER DEFENSE LLC" },
        { prefix: "HRAC", company: "HENRY REPEATING ARMS COMPANY" },
        { prefix: "TALO HRAC", company: "HENRY REPEATING ARMS COMPANY" },
        { prefix: "HRACW", company: "HENRY WISCONSIN LLC" },
        { prefix: "HTG", company: "HERITAGE MANUFACTURING, INC." },
        { prefix: "HEX", company: "HEXMAG" },
        { prefix: "MKS", company: "MKS SUPPLY, LLC." },
        { prefix: "HIVIZ", company: "NORTH PASS LTD (HIVIZ)" },
        { prefix: "HKS", company: "HKS PRODUCTS" },
        { prefix: "HOG", company: "HOGUE GRIPS" },
        { prefix: "HOLO", company: "HOLOSUN" },
        { prefix: "HDEF", company: "HONOR DEFENSE" },
        { prefix: "HOOY", company: "HOOYMAN" },
        { prefix: "HORN", company: "HORNADY" },
        { prefix: "HL", company: "HONEYWELL SAFETY PRODUCTS US" },
        { prefix: "HPR", company: "HPR AMMUNITION" },
        { prefix: "HSPI", company: "H-S PRECISION, INC." },
        { prefix: "HUN", company: "HUNTER COMPANY" },
        { prefix: "HSP", company: "HUNTER'S SPECIALTIES, INC." },
        { prefix: "JS", company: "HUNTER'S SPECIALTIES, INC." },
        { prefix: "HSM", company: "HSM/HUNTING SHACK INC." },
        { prefix: "HUSK", company: "HUSKEMAW OPTICS" },
        { prefix: "IFG", company: "IFG LLC" },
        { prefix: "IO", company: "INTER ORDNANCE" },
        { prefix: "IAC", company: "INTERSTATE ARMS CORPORATION" },
        { prefix: "ITS", company: "INTREPID TACTICAL SOLUTIONS" },
        { prefix: "IOSSO", company: "IOSSO PRODUCTS" },
        { prefix: "HOLDEN", company: "IRONSIGHTER CO." },
        { prefix: "ITH", company: "ITHACA GUN COMPANY" },
        { prefix: "IWI", company: "IWI US, INC." },
        { prefix: "JBA", company: "CAPTECH INTERNATIONAL LLC" },
        { prefix: "JRC", company: "LDB SUPPLY LLC" },
        { prefix: "KA", company: "KAHR ARMS" },
        { prefix: "KEL", company: "KEL-TEC CNC INDUSTRIES, INC." },
        { prefix: "KER", company: "KERSHAW KNIVES" },
        { prefix: "KING", company: "KINGSTON ARMORY" },
        { prefix: "KON", company: "KONUS" },
        { prefix: "KRISS", company: "KRISS USA,  INC" },
        { prefix: "LN", company: "LANCER SYSTEMS, LP" },
        { prefix: "LS", company: "LANSKY SHARPENERS" },
        { prefix: "LANTAC", company: "LANTAC USA LLC" },
        { prefix: "LG", company: "LASER GENETICS" },
        { prefix: "LL", company: "LASERLYTE" },
        { prefix: "LM", company: "LASERMAX" },
        { prefix: "UTG", company: "LEAPERS, INC." },
        { prefix: "LEE", company: "LEE PRECISION INC" },
        { prefix: "ISSC", company: "LEGACY SPORTS INT'L, LLC" },
        { prefix: "LSI", company: "LEGACY SPORTS INT'L, LLC" },
        { prefix: "LEU", company: "LEUPOLD & STEVENS INC" },
        { prefix: "RED", company: "LEUPOLD & STEVENS INC" },
        { prefix: "LIB", company: "LIBERTY AMMUNITION" },
        { prefix: "LAI", company: "LIBERTY ARMS INTERNATIONAL LLC" },
        { prefix: "LF", company: "LIGHTFIELD AMMUNITION CORP" },
        { prefix: "LH", company: "LIONHEART INDUSTRIES, LLC" },
        { prefix: "LWRC", company: "LWRC INTERNATIONAL" },
        { prefix: "ADTAC", company: "LYMAN" },
        { prefix: "AZOOM", company: "LYMAN" },
        { prefix: "LYM", company: "LYMAN" },
        { prefix: "PAC", company: "LYMAN" },
        { prefix: "TAC", company: "LYMAN" },
        { prefix: "TRIUS", company: "LYMAN" },
        { prefix: "MM", company: "M&M LLC (Cogunsales)" },
        { prefix: "MACE", company: "MACE PERSONAL DEFENSE &" },
        { prefix: "LULA", company: "MAGLULA LTD." },
        { prefix: "MR", company: "MAGNUM RESEARCH, INC" },
        { prefix: "MTA", company: "MAGTECH AMMUNITION CO INC" },
        { prefix: "SB", company: "MAGTECH AMMUNITION CO INC" },
        { prefix: "MAKO", company: "MAKO GROUP, THE" },
        { prefix: "MANTA", company: "MANTA" },
        { prefix: "MAR", company: "MARLIN FIREARMS" },
        { prefix: "ML", company: "MASTER LOCK COMPANY LLC" },
        { prefix: "MPA", company: "MASTERPIECE ARMS" },
        { prefix: "MEC", company: "MAYVILLE ENGINEERING (MEC)" },
        { prefix: "MECGAR", company: "MEC-GAR USA, INC." },
        { prefix: "MGI", company: "MG INDUSTRIES, INC." },
        { prefix: "MI", company: "MI-MIDWEST INDUSTRIES, INC." },
        { prefix: "MNX", company: "MINOX USA, INC." },
        { prefix: "MFT", company: "MISSION FIRST TACTICAL" },
        { prefix: "MK", company: "MOISTURE KING" },
        { prefix: "FIME", company: "FIME GROUP" },
        { prefix: "MAV", company: "O.F. MOSSBERG & SONS INC" },
        { prefix: "MOSS", company: "O.F. MOSSBERG & SONS INC" },
        { prefix: "TALO MOSS", company: "O.F. MOSSBERG & SONS INC" },
        { prefix: "MOUL", company: "PRADCO OUTDOOR BRANDS" },
        { prefix: "MTM", company: "MTM MOLDED PRODUCTS CO" },
        { prefix: "NIKKO", company: "CENTURION INTERNATIONAL, LTD" },
        { prefix: "NIK", company: "NIKON INC" },
        { prefix: "NORD", company: "NORDIC COMPONENTS" },
        { prefix: "NOREEN", company: "NOREEN FIREARMS" },
        { prefix: "NAA", company: "NORTH AMERICAN ARMS INC" },
        { prefix: "TALO NAA", company: "NORTH AMERICAN ARMS INC" },
        { prefix: "NOS", company: "NOSLER INCORPORATED" },
        { prefix: "SSA", company: "NOSLER INCORPORATED" },
        { prefix: "OEM", company: "OEM" },
        { prefix: "OAI", company: "OLYMPIC ARMS INC." },
        { prefix: "OSS", company: "OPERATORS SUPPRESSOR SYSTEMS" },
        { prefix: "OTIS", company: "OTIS TECHNOLOGY, INC." },
        { prefix: "OBF", company: "OUTBACK FLASHLIGHTS" },
        { prefix: "OC", company: "OUTDOOR CONNECTION" },
        { prefix: "OZON", company: "OZONICS" },
        { prefix: "PAL", company: "PALCO SPORTS" },
        { prefix: "PO", company: "PARA USA" },
        { prefix: "POF", company: "PATRIOT ORDNANCE FACTORY" },
        { prefix: "PEARCE", company: "PEARCE GRIP, INC" },
        { prefix: "PELICAN", company: "PELICAN" },
        { prefix: "PEL", company: "3M COMPANY" },
        { prefix: "PR", company: "PETE RICKARD INC" },
        { prefix: "PT", company: "PHOENIX TECHNOLOGY LTD." },
        { prefix: "PLANO", company: "PLANO MOLDING CO." },
        { prefix: "PMC", company: "PMC AMMUNITION, INC." },
        { prefix: "PRED", company: "PREDATOR TACTICS" },
        { prefix: "PRIMOS", company: "BUSHNELL INC." },
        { prefix: "PE", company: "ALTUS BRANDS LLC" },
        { prefix: "PM", company: "PRO-MAG MFG INC" },
        { prefix: "PRO", company: "PRO SHOT PRODUCTS" },
        { prefix: "PTAC", company: "STEEL WILL INVESTMENTS INC" },
        { prefix: "PTR", company: "PTR INDUSTRIES, INC." },
        { prefix: "PYRA", company: "PYRAMEX SAFETY PRODUCTS" },
        { prefix: "RAD", company: "RADIANS" },
        { prefix: "REAL", company: "REVO BRAND GROUP, LLC" },
        { prefix: "RWB", company: "RED, WHITE & BLUE, LLC" },
        { prefix: "REM", company: "REMINGTON ARMS COMPANY" },
        { prefix: "RG", company: "RGUNS" },
        { prefix: "ROB", company: "ROBERTS DEFENSE" },
        { prefix: "AUA", company: "ARMSCOR PRECISION INTERNATIONA" },
        { prefix: "RIA", company: "ARMSCOR PRECISION INTERNATIONA" },
        { prefix: "RRA", company: "ROCK RIVER ARMS, INC." },
        { prefix: "ROG", company: "ROGERS HOLSTER COMPANY, LLC" },
        { prefix: "ROS", company: "BRAZTECH INTL (ROSSI)" },
        { prefix: "RUG", company: "STURM, RUGER & COMPANY, INC" },
        { prefix: "TALO RUG", company: "STURM, RUGER & COMPANY, INC" },
        { prefix: "TPD", company: "TORNADO PERSONAL DEFENSE" },
        { prefix: "RS", company: "RUGGED SUPRESSORS" },
        { prefix: "RAA", company: "ICON MARKETING GROUP" },
        { prefix: "RWC", company: "TRANSPORTATION ALLIANCE BANK" },
        { prefix: "SAB", company: "SECURITY EQUIPMENT CORP" },
        { prefix: "SACK", company: "SACK-UPS" },
        { prefix: "BIA", company: "SAFARILAND,LLC" },
        { prefix: "BREAK", company: "SAFARILAND,LLC" },
        { prefix: "BSQ", company: "SAFARILAND,LLC" },
        { prefix: "KB", company: "SAFARILAND,LLC" },
        { prefix: "SAF", company: "SAFARILAND,LLC" },
        { prefix: "SAGEN", company: "SAGEN INC." },
        { prefix: "SAV", company: "SAVAGE ARMS, INC." },
        { prefix: "SCCY", company: "SCCY INDUSTRIES, LLC" },
        { prefix: "SC", company: "VENTCO INC (SHOOTERS CHOICE)" },
        { prefix: "SIE", company: "SIERRA BULLETS, L.P." },
        { prefix: "SIG", company: "SIG SAUER, INC." },
        { prefix: "TALO SIG", company: "SIG SAUER, INC." },
        { prefix: "FF", company: "SELLMARK CORPORATION" },
        { prefix: "PULSAR", company: "SELLMARK CORPORATION" },
        { prefix: "SM", company: "SELLMARK CORPORATION" },
        { prefix: "ST", company: "SIGHTRON" },
        { prefix: "S9", company: "SIGNAL 9 DEFENSE" },
        { prefix: "SIL", company: "SILENCERCO, LLC" },
        { prefix: "SIMS", company: "SIMS VIBRATION LAB (LIMB SAV)" },
        { prefix: "SFS", company: "SLIDE FIRE SOLUTIONS, LP" },
        { prefix: "SW", company: "SMITH & WESSON" },
        { prefix: "TALO SW", company: "SMITH & WESSON" },
        { prefix: "SOG", company: "SOG" },
        { prefix: "SONIC", company: "SONIC BOOM EXPLODING TARGETS" },
        { prefix: "SBLOOM", company: "SOUTHERN BLOOMER MFG CO" },
        { prefix: "SPR", company: "SPRINGFIELD ARMORY" },
        { prefix: "SO", company: "STACK-ON PRODUCTS, CO." },
        { prefix: "SML", company: "STANDARD MANUFACTURING CO LLC" },
        { prefix: "STOP", company: "PHALANX DEFENSE SYSTEMS" },
        { prefix: "STEYR", company: "STEYR ARMS" },
        { prefix: "STORM", company: "PELICAN STORM CASES" },
        { prefix: "STREAM", company: "STREAMLIGHT, INC." },
        { prefix: "SUN", company: "SUN OPTICS USA" },
        { prefix: "SF", company: "SGM TACTICAL LLC" },
        { prefix: "SWIFT", company: "SWIFT BULLET COMPANY" },
        { prefix: "TANN", company: "TANNERITE" },
        { prefix: "TAPCO", company: "TAPCO" },
        { prefix: "TAFA", company: "TARGET-FACTORY" },
        { prefix: "TAU", company: "TAURUS INTERNATIONAL MFG" },
        { prefix: "SCHRADE", company: "TAYLOR BRANDS LLC" },
        { prefix: "TAY", company: "TAYLOR BRANDS LLC" },
        { prefix: "TF", company: "TAYLOR'S & COMPANY, INC." },
        { prefix: "TC", company: "THOMPSON CENTER" },
        { prefix: "TCLIP", company: "TECHNA CLIP" },
        { prefix: "TGM", company: "TECHNICAL GRINDING AND" },
        { prefix: "HORT", company: "TENPOINT CROSSBOW TECHNOLOGIES" },
        { prefix: "TP", company: "TENPOINT CROSSBOW TECHNOLOGIES" },
        { prefix: "SAKO", company: "BERETTA USA CORP (TIKKA)" },
        { prefix: "TIK", company: "BERETTA USA CORP (TIKKA)" },
        { prefix: "TINKS", company: "PAT ACQUISITON, LLC (TINKS)" },
        { prefix: "TRAD", company: "TRADITIONS MUZZLELOADING" },
        { prefix: "TRI", company: "TRIJICON, INC." },
        { prefix: "TRIMAG", company: "ALANGATOR, LLC" },
        { prefix: "TSA", company: "TRISTAR SPORTING ARMS, LTD" },
        { prefix: "TROY", company: "TROY INDUSTRIES" },
        { prefix: "TG", company: "TRUGLO" },
        { prefix: "MAXX", company: "TULAMMO USA, INC." },
        { prefix: "TA", company: "TULAMMO USA, INC." },
        { prefix: "TIF", company: "BUDS GUN SHOP" },
        { prefix: "UD", company: "ULTRADOT DISTRIBUTION" },
        { prefix: "UMAX", company: "ULTRAMAX AMMUNITION" },
        { prefix: "UMAREX", company: "UMAREX USA" },
        { prefix: "USFA", company: "USFA/ZIPFACTORY, LLC" },
        { prefix: "USPK", company: "" },
        { prefix: "USSG", company: "USSG INC." },
        { prefix: "UTAS", company: "UTAS-USA" },
        { prefix: "VV", company: "PIONEER RESEARCH" },
        { prefix: "VC", company: "VERSACARRY" },
        { prefix: "LAS", company: "VIRIDIAN GREEN LASER SIGHTS" },
        { prefix: "BCMM", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "CCI", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "CHAMP", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "GUNS", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "OUTERS", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "RAM", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "RCBS", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "SHOOT", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "SPEER", company: "VISTA OUTDOOR SALES LLC" },
        { prefix: "TALO WAL", company: "WALTHER ARMS,INC." },
        { prefix: "WAL", company: "WALTHER ARMS,INC." },
        { prefix: "WAR", company: "WARNE" },
        { prefix: "WASP", company: "WASPCAM" },
        { prefix: "WBY", company: "WEATHERBY INC" },
        { prefix: "WEAVER", company: "WEAVER" },
        { prefix: "WR", company: "WILDLIFE RESEARCH CENTER, INC." },
        { prefix: "WIN", company: "WINCHESTER ARMS" },
        { prefix: "WW", company: "WINDHAM WEAPONRY" },
        { prefix: "WISE", company: "WISE FOODS" },
        { prefix: "WMD", company: "WMD GUNS" },
        { prefix: "WDY", company: "INVENTIVE DESIGN STUDIO LLC" },
        { prefix: "XP", company: "X PRODUCTS LLC" },
        { prefix: "YHM", company: "YANKEE HILL MACHINE CO., INC." },
        { prefix: "ZS", company: "CARL ZEISS SBE, LLC." },
        { prefix: "ZEN", company: "ZENITH FIREARMS" }
      ]
    end

  end
end
